# Generated by Django 3.1.6 on 2021-03-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catgory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='note',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='vendor',
        ),
    ]
